NeuralEnsemble/PyNN

- src/nest/cells.py
- src/nest/synapses.py
In the next NEST release, the internal parameter name 'node_type' will changed to 'element_type'. With this commit the change is reflected in PyNN.
> Change NEST 'node_type' to 'element_type'

- .gitignore
.spyderproject was missing in .gitignore. Spyder is a python IDE, and it's awseome, by the way ;)
> added spyder project files to .gitignore

- src/parameters.py
In the exception message, the "got" and "expected" types were backwards. Super minor bug, I know, but hopefully this'll save someone an hour of confusion!
> Fixed exception message when a parameter fails a type validation check.

- doc/connections.txt
- src/nest/random.py
- src/neuron/random.py
- src/random.py
...to avoid clashing with Python keyword lambda.
(The original idea was to require `RandomDistribution("poisson", **{"lambda": 5})` but on reflection triggered by #347 this is a terrible idea).
> Rename the parameter "lambda" of the Poisson distribution to "lambda_"

- src/neuron/nmodl/izhikevich.mod
According to Michael's response to this bug I filed on the NEURON forum, https://www.neuron.yale.edu/phpBB/viewtopic.php?f=16&t=3278, the solve method for the Izhikevich.mod file should be `derivimplicit` not `cnexp` (which is only meant to be used for single state variable equations)
> The cnexp method is invalid for that derivative equation.
The cnexp method requires that each y' equation be linear and involve no other state than y.
That is, cnexp was intended for use only in HH style gating equations where the form looked like
m' = (minf(v) - m)/mtau(v)
or
m' = bm(v)*(1. - m) - am(v)*m
> For general (nonlinear and coupled state ) equations, use derivimplicit. I need to change the nmodl translator to generate an error message if the equation forms do not
satisfy the cnexp requirements …
> switched solve method of Izhikevich NMODL from cnexp to derivimplicit

- src/brian/recording.py
Fixes an issue where plots of recorded neurons would not match their labels.
This is due to:
ids = set([id for id in ids if id.local])
in PyNN / src / recording / __init__.py, line 197, which in some cases changes the order of neurons, e.g. numpy.fromiter(set(numpy.array([13,14,15,16])) becomes array([16, 13, 14, 15]). Re-sorting the array before sending it to the Brian recording device fixed this for me.
> sort neurons before recording by Brian

- pyNN/nest/simulator.py
The delay can't be set for a `gap_junction`, since this synapse model has no delay.
> This Pull Request fixes #385

- doc/releases/0.8.0.txt
Sorry, I should have waited a bit longer before the previous commit. There are a few more syntax errors, fixed here.
> Fix syntax errors in 0.8 changelog

- pyNN/utility/plotting.py
Same as max_index but with a min_index.
Called the sys.maxint to set the best maximum lower boundary as possible.
> Add lower bound index for plot_spiketrains

- pyNN/nest/recording.py
- pyNN/nest/standardmodels/electrodes.py
This PR removes the last usages of the deprecated NEST connection routines `DivergentConnect` and `ConvergentConnect`. It fixes #414 .
This works with NEST 2.10., therefore I request to merge into master.
> Remove old connect routines

- .travis.yml
- ci/install_nest.sh
- pyNN/nest/simulator.py
This PR supersedes #413 .
In NEST, min_delay is no longer set in the defaults of each synapse but min_delay is set globally in the NEST kernel.
This fixes #411 .
In addition, the install_nest.sh script for Travis was changed to download and build the current master from [https://github.com/nest/nest-simulator](https://github.com/nest/nest-simulator). To achieve this, I removed the possibility to fall back on cached code so that Travis always checks with the current master branch of NEST.
> Fix min delay error

- doc/reference/connectors.txt
- pyNN/brian/projections.py
- pyNN/common/projections.py
- pyNN/nest/projections.py
- pyNN/neuron/projections.py
- test/system/scenarios/test_connectors.py
- test/unittests/test_projection.py
to control the combination of properties when there are multiple synapses connecting a pair of neurons (implements #362)
> Added a `multiple_synapses` flag to `Projection.get(..., format="array")`

- pyNN/nest/populations.py
- pyNN/nest/standardmodels/cells.py
- pyNN/neuron/cells.py
- pyNN/neuron/nmodl/gammastim.mod
- pyNN/neuron/standardmodels/cells.py
- pyNN/standardmodels/cells.py
- test/system/scenarios/test_cell_types.py
with implementations in NEST and NEURON backends, and unit test. cf #386 
**NEST**
**NEURON**
Note that the distribution for NEST is slightly distorted for high rates, since spikes can only occur on time-step boundaries.
> Added `SpikeSourceGamma` model.

- ci/install.sh
- doc/developers/contributing.txt
- test/system/scenarios/__init__.py
- test/system/scenarios/registry.py
**Background:** System tests defined in the `scenarios` directory are treated as a single test (`test_scenarios()`) while running nosetests.
The update proposed here attempts to allow the user to selectively run nosetests for the tests of interest in the `scenarios` directory. This makes use of the `nose-testconfig` plugin. Details here: https://pypi.python.org/pypi/nose-testconfig. It basically allows passing of test-specific (or test-run specific) configuration data to the tests being executed.
This can be installed with:
`pip install nose-testconfig`
We use this here to either specify the name of the testfile (containing the tests that we are interested in), or just the name of a specific test.
Examples:
**- To run all tests within a file named 'test_electrodes' located inside …
> Changes to allow running nosetests for specific tests from system/scenarios

- pyNN/neuron/recording.py
- test/system/scenarios/test_electrodes.py
Replaces int() with numpy.rint() to resolve #483 
Test case created for future checks.
> Fix for issue #483: evaluation of expected vector length rectified

- pyNN/neuron/simulator.py
- pyNN/neuron/standardmodels/electrodes.py
- test/system/scenarios/test_electrodes.py
This fix rectifies:
- DCSource 
- StepCurrentSource
under NEURON. It fixes the issue for simulations that are split into multiple runs.
Now output is equivalent when running:
```
run(200.0)
```
or
```
run(100.0)
run(100.0)
```
> Fixes issue #487: Updates _update_iclamp() for NEURON

- pyNN/neuron/standardmodels/electrodes.py
- test/system/scenarios/test_electrodes.py
Had overlooked a boundary condition in the fix under #488. This is handled here. Appropriate sub-test case has been added to identify this scenario.
> Updates fix for issue #487 - handles boundary condition

- pyNN/common/populations.py
- pyNN/common/procedural_api.py
- test/system/scenarios/test_recording.py
- test/unittests/test_lowlevelapi.py
This attempts to fix issues #449, #490 and #491.
**issue #491 (sim.record() not working properly for individual cells from a population)**
----------------------------------------------------------------------------------------
The recording is now updated to handle individual cells as PopulationView.
PopulationView class is accordingly updated to include an 'annotations' attribute.
**issue #449, #490  (Population recording not working properly)**
----------------------------------------------------------------------------------------
`sim.record()` invoked the following (in order):
```
pyNN/common/procedural_api.py
pyNN/common/populations.py
pyNN/recording/__init__.py
```
`pop.record()` invoked the following (in order):
```
pyNN/common/populations.py
pyNN/recording/__init__.py
``` …
> Fixes #449, #490, #491: Corrects simulator and population recording

- pyNN/common/populations.py
- pyNN/standardmodels/cells.py
**Addresses issue #459** 
find_units() should now return units for both:
- recordable variables, and
- neuron parameters
for all standard models
> Fixes 459: Extends find_units() for neuron parameters

- pyNN/brian/__init__.py
- test/system/scenarios/test_recording.py
Fix for issue #499.
Removes `simulator.state.clear()` from `sim.end()` for Brian.
> Fixes issue #499: updates sim.end() for Brian

- pyNN/nest/standardmodels/electrodes.py
- test/system/scenarios/test_electrodes.py
Fixes #497 (see for details)
Tweaks the value of `phase` supplied to NEST ACSource so as to remain consistent with other simulators. The test case for this fix requires the recording of current profiles. As the final current recording implementation is currently unavailable in the 'master' branch, the test has been excluded for the time being. Tested locally to ensure it works.
> Fixes #497: tweaks phase for NEST ACSource

- pyNN/nest/standardmodels/electrodes.py
Continuing on the discussion under issue #482 :
The sequence of steps for NEST is now as follows:
(consider `dt = min_delay = 0.1 ms`)
1) User inputs a time series, e.g.
`times = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]`
2) `_delay_correction()` will subtract `min_delay` (set to 0.0, if result is negative), so
`times = [0.0, 0.0, 0.1, 0.2, 0.3, 0.4]`
3) We now scan the time series to find the last element matching `dt`. This corresponds to the first timestamp that can be used by NEST for current injection. All prior timestamps (and corresponding amplitudes) are removed. So we have
`times = [0.1, 0.2, 0.3, 0.4]`
A thorough test case for the StepCurrentSource across all simulators will be developed for issue #512 , and thus the same is avoided here.
The fix has been tested for the issue reported for …
> Fixes #482 - Handles timestamps of StepCurrentSource for NEST

- pyNN/brian/cells.py
- pyNN/nest/populations.py
- pyNN/neuron/cells.py
- test/system/scenarios/test_cell_types.py
> Raise an Exception if the spike times given to SpikeSourceArray are not ordered

- examples/Potjans2014/plotting.py
- examples/Potjans2014/validation_microcircuit.py
I have made two changes:
1. in `plotting.py` I have added
``import matplotlib
matplotlib.use('Agg') ``
2. I have created a `validation_microcircuit.py` which contains the class `Potjans2014Microcircuit`. The class is mostly based on `microcircuit.py` with some modifications. To use it with `sciunit` you just need to uncomment lines **27-28** and **33-34** and comment line **36**.
3. To use just
`from validation_microcircuit import Potjans2014Microcircuit as pm`
`model = pm()`
`model.produce_spiketrain()`
> SciUnit interface for the Potjans2014 model

- doc/data_handling.txt
- pyNN/brian/standardmodels/electrodes.py
- pyNN/nest/electrodes.py
- pyNN/nest/standardmodels/electrodes.py
- pyNN/neuron/standardmodels/electrodes.py
- pyNN/standardmodels/__init__.py
- test/system/scenarios/test_electrodes.py
This fix attempts to ensure that the StepCurrentSource times are handled similarly by all the simulators. The details are as discussed in #512 .
@apdavison : The test case needed as much as work as the fix itself here (lots of simulator specific checks). Do take a look and let me know if it could have been done better. Was the first time that I actually wanted an error raised as a check for proper functioning, and so not sure if this was the best approach (suggestions on StackOverflow seemed more involved).
> Fix for #512

- pyNN/connectors.py
- pyNN/parameters.py
- pyNN/random.py
- pyNN/recording/__init__.py
- test/unittests/test_parameters.py
- test/unittests/test_random.py
There are two changes here:
(1) previously, a random number generator with `parallel_safe=False` would always draw a reduced number of values when run with >1 MPI processes, according to the number of processes, unless the `mask_local` parameter was set to `False`. Now, a mask must be explicitly provided if you want to draw a reduced number of values (i.e. only those values consumed on that node), `mask` (renamed from `mask_local`) is either an array, or None, and can no longer take the value `False`.  
(2) moved the lazyarray behaviour for `RandomDistribution` from the lazyarray package to PyNN, to keep all the rng-related logic in one place.
> Simplify interaction of random number generators and lazyarray

- examples/Potjans2014/plotting.py
`layer` must be integer valued or else `layer_list[layer]` will throw an exception, at least in versions of Python the don't coerce floats to ints automatically.
> Fixed to avoid float-valued list indices error

- .gitignore
- ci/install.sh
- ci/test_script.sh
- requirements.txt
- setup.py
- Prefer setuptools if available
- update setup.py to include run time dependencies, optional dependencies, and dependencies needed by tests.
> Updates to setup.py and other misc tweaks

- doc/index.txt
- doc/publications.txt
Addresses #592
@apdavison I realized that the link I sent you was from a page that belongs to the Neural Ensemble site (http://neuralensemble.org/trac/PyNN/wiki/Publications).
So, not sure where you want this to live in the PyNN docs, but I added a "publications about..." entry on the index toctree under "examples", and a corresponding `publications.txt` in `./doc`.
It worked for me when I built it locally and I kept the formatting more or less the same (plus or minus some line breaks). Let me know how it looks to you.
> Add publications to docs

- pyNN/brian/standardmodels/electrodes.py
Resolves #631 
**Note:** Merge PR #633 and #635 before this one.
I have renamed the earlier `record()` and `_get_data()` methods to `_record_old()` and `_get_data_old()`, respectively. These would come in handy to test the electrode currents for accuracy, i.e. compare actual current getting injected into cell vs current being ad-hoc evaluated for display (DC, Step) / current being separately recorded (AC, Noisy).
In the new implementation, `record()` does not serve any purpose. As an implementation of this method is required for Brian backend, I have simply left it empty (pass).
> Fixes issue 631: revamps brian electrode recording

- examples/update_spike_source_array.py
- pyNN/neuron/cells.py
- pyNN/neuron/recording.py
- test/system/scenarios/test_cell_types.py
#645 - "Only spike times from last update are recorded when updating neuron.SpikeSourceArray"
> Fix for #645 

- test/benchmarks/Benchmark_PyNN-0.8dev_FixedNumberPost.py
Not sure if it's planned to keep this benchmark…
Changes:
* `Population.record()` nowadays needs to specify a variable name
* `var = range(...)` behave differently in Python 3…
* neo wants us to use non-ASCII, e.g. pkl for recording to files.
> Fix Benchmark_PyNN-0.8dev_FixedNumberPost.py

- pyNN/utility/__init__.py
* making it optional
* it is False by default to not change the behavior
> use ISO8601 for normalized filenames

- pyNN/nest/__init__.py
- pyNN/nest/extensions/pynn_extensions.cpp
- pyNN/nest/projections.py
- pyNN/nest/simulator.py
- test/system/scenarios/test_connection_handling.py
We now invalidate the connection cache whenever connections are added to any Projection (cf #672)
The PR also includes a regression test. To avoid the constant warnings, this PR also changes the default verbosity level to "error", however if would be nice if we could turn off this warning specifically.
> Fix problem due to changes in connection sorting in NEST (#672)

- pyNN/nest/projections.py
We noticed that since NEST 2.16, the nest GetConnections function takes a lot more time to run. As the GetConnections function is called in the PyNN function convergent_connect (in nest.projections) for connections with specific parameters other than delay and weight, this created a big slow down in our model during the building of the connections. That's why I modified this PyNN code to limit the call of the nest GetConnections function. We obtained a great speed up in our model during the building of connections (from 2 whole days to 45 minutes), and the new version of the code seems to pass all the PyNN tests. Hence I was thinking that sharing these modification could be maybe interesting for you.
In the code I wrote, the GetConnections function is called only if the common synapse …
> Modification in convergent_connect to speed up the building of connections

- pyNN/recording/__init__.py
> Ignore previous calls of `record(spikes)` when checking for consistency of sampling interval

- setup.py
Fixes installation problem on Windows systems.
Currently users might see the installation getting stuck on running
`pip install pyNN`
or locally
`python setup.py install`
Gets stuck at this stage:
This arises from this method in setup.py
```python
def run_command(path, working_directory):
p = subprocess.Popen(path, shell=True, stdin=subprocess.PIPE,
stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
universal_newlines=True,
cwd=working_directory)
result = p.wait()
stdout = p.stdout.readlines()
return result, stdout
```
On investigating, it was found that the execution gets stuck at `result = p.wait()`
The use of `wait()` is potentially problematic. As mentioned in the [docs](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait):
This PR takes the above suggestion of …
> update subprocess call in setup.py

- pyNN/common/projections.py
Also change the AssertionError when checking the synapse_type argument to a TypeError
Closes #692
> Check the type of the connector argument to Projection, and provide a user-friendly error message

- pyNN/utility/plotting.py
Change fig.show() to plt.show()
Note that this will block; figure needs to be closed for rest of code to continue.
In regular usage, I presume Figure.save() to be more used.
> Change Figure.show()

- pyNN/nest/cells.py
This was causing NESTML-generated models to fail upon instantiation, as "model_id" is a gettable, but not settable parameter.
> Add model_id to ignored parameters for NEST

- pyNN/brian2/recording.py
- pyNN/mock/recording.py
- pyNN/nest/recording.py
- pyNN/neuroml/recording.py
- pyNN/neuron/__init__.py
- pyNN/neuron/recording.py
- pyNN/neuron/simulator.py
- pyNN/neuron/standardmodels/electrodes.py
- pyNN/recording/__init__.py
- pyNN/utility/plotting.py
- test/unittests/test_neuron.py
for NEURON with cvode or for BrainScaleS-2
> Add support for irregular sampling intervals when recording

- pyNN/utility/plotting.py
Prior to this commit, running small_network.py --plot-figure will fail with 'Unable to convert between units of "dimensionless" and "ms"' error. This commit also fixes the x-y order in plotting.
Before:
```
raise ValueError(
ValueError: Unable to convert between units of "dimensionless" and "ms"
```
After:
> Fix quantities error and x-y order in plotting

- doc/pyplots/neo_example.py
- pyNN/recording/__init__.py
- pyNN/serialization/sonata.py
When moving to using the new SpikeTrainList object in Neo, the annotations weren't fully harmonized between the "create from tuple" and "create from list" pathways, which led to the following error when using pyNN.nest with MPI:
```
$ mpirun -np 2 `which python` small_network.py nest
Traceback (most recent call last):
File "/home/andrew/dev/PyNN/examples/small_network.py", line 88, in <module>
cells.write_data(filename, annotations={'script_name': __file__})
File "/home/andrew/dev/PyNN/pyNN/common/populations.py", line 502, in write_data
self.recorder.write(variables, io, gather, self._record_filter, clear=clear,
File "/home/andrew/dev/PyNN/pyNN/recording/__init__.py", line 469, in write
data = self.get(variables, gather, filter_ids, clear, annotations=annotations,
File …
```
> Harmonize spike train annotations

- pyNN/brian2/standardmodels/cells.py
- pyNN/neuron/cells.py
> Fix point neuron problems with pyNN.neuron and pyNN.brian2 modules 

- doc/conf.py
Fixes #791
Changes:
- `html_theme = 'nature'` to `html_theme = 'sphinxawesome_theme'`
- Screenshot after changes:
> Fix content overflow in doc sidebar
