- .travis.yml
- README.rst
- ci/install_brian.sh
- ci/install_nest.sh
- ci/install_neuron.sh
- ci/test_script.sh
- test/system/scenarios/test_cell_types.py
- test/system/test_brian.py
- test/system/test_hardware_brainscales.py
> Run system tests with Travis CI

- .travis.yml
- ci/install.sh
- ci/install_brian.sh
- ci/install_nest.sh
- ci/install_neuron.sh
- ci/test_script.sh
- test/hardware/unittests/test_population.py
- test/system/test_nest.py
- test/system/test_neuron.py
- test/unittests/test_neuron.py
This also installs NEST 2.10 and NEURON 7.4 for Python 3.5 as well as 2.7, although the system tests are being skipped for Python 3.5 for a reason still to be determined.
> Modify Travis CI configuration to use the Trusty build environment

- pyNN/common/populations.py
- pyNN/parameters.py
also fixes a bug in `Population.get(..., gather=True)`
> Fix for #428

- AUTHORS
- examples/gif_neuron.py
- pyNN/nest/__init__.py
- pyNN/nest/populations.py
- pyNN/nest/recording.py
- pyNN/nest/simulator.py
- pyNN/nest/standardmodels/cells.py
- pyNN/neuron/cells.py
- pyNN/neuron/nmodl/gif.mod
- pyNN/neuron/standardmodels/cells.py
- pyNN/standardmodels/cells.py
for NEST and NEURON backends. Brian implementation still needed.
Requires development version of NEST (Github master branch).
Only simple, cond-exp synapses for now.
> Generalized integrate-and-fire model

- pyNN/brian/standardmodels/electrodes.py
- pyNN/neuron/standardmodels/electrodes.py
- test/system/scenarios/test_electrodes.py
This PR fixes issues #437, #442, #445, #451, #465 
Test cases developed for all except #465. Pending implementation of feature in NEST.
> Fixes issues #437, #442, #445, #451, #465

- .gitignore
- examples/mc/current_injection_mc.py
- examples/mc/current_injection_mc_swc.py
- pyNN/common/populations.py
- pyNN/connectors.py
- pyNN/mock/recording.py
- pyNN/models.py
- pyNN/morphology.py
- pyNN/nest/recording.py
- pyNN/neuron/__init__.py
- pyNN/neuron/cells.py
- pyNN/neuron/populations.py
- pyNN/neuron/projections.py
- pyNN/neuron/recording.py
- pyNN/neuron/simulator.py
- pyNN/neuron/standardmodels/cells.py
- pyNN/neuron/standardmodels/electrodes.py
- pyNN/neuron/standardmodels/ion_channels.py
- pyNN/parameters.py
- pyNN/recording/__init__.py
- pyNN/standardmodels/__init__.py
- pyNN/standardmodels/cells.py
- pyNN/standardmodels/ion_channels.py
- pyNN/utility/plotting.py
- test/unittests/test_neuron.py
- test/unittests/test_recording.py
**Do not merge this pull request!**
The purpose of this PR is to be able to easily see and comment on the changes proposed for multicompartmental modelling, with respect to the master branch.
> Experiments with multicompartmental API

- pyNN/nest/projections.py
- test/system/scenarios/test_parameter_handling.py
- test/system/test_nest.py
("Accessing U with with_address=False throws error")
> Fix for #505

- pyNN/brian/standardmodels/electrodes.py
- pyNN/nest/electrodes.py
- pyNN/neuron/standardmodels/electrodes.py
- pyNN/standardmodels/__init__.py
- test/system/scenarios/test_electrodes.py
for better consistency with `Population.get_data()`
> Modify `CurrentSource.get_data()` to return a Neo signal object

- .travis.yml
- ci/install_nest.sh
- pyNN/nest/__init__.py
- pyNN/nest/extensions/simple_stochastic_connection.h
- pyNN/nest/extensions/stochastic_stp_connection.h
- pyNN/nest/extensions/stochastic_stp_connection_impl.h
- pyNN/nest/projections.py
- pyNN/nest/simulator.py
- pyNN/recording/__init__.py
- test/system/scenarios/test_connectors.py
> Support for NEST 2.16.0

- doc/developers/governance.txt
- doc/developers_guide.txt
- doc/publications.txt
> Added document on project governance

- pyNN/connectors.py
- test/unittests/test_connectors_serial.py
> FromListConnector now accepts empty lists, as it is supposed to.

- pyNN/brian/standardmodels/electrodes.py
- pyNN/neuron/standardmodels/electrodes.py
- test/system/scenarios/test_electrodes.py
- test/system/test_brian.py
Test cases for issues #630 , #631 and #634 
Merge this after their PRs are merged.
> Tests for issues 630, 631, 634

- pyNN/brian/projections.py
- pyNN/common/populations.py
- pyNN/connectors.py
- test/system/scenarios/test_connectors.py
> Fix for #622

- pyNN/nest/projections.py
> Fix problem with setting STDP parameters for inhibitory synapses with pyNN.nest

- pyNN/connectors.py
- pyNN/nest/__init__.py
- pyNN/nest/connectors.py
- pyNN/nest/simulator.py
- pyNN/nest/standardmodels/synapses.py
- pyNN/nest/synapses.py
…, to avoid scaring users unecessarily - see #669
> Move warnings about missing features to the point where they are used

- doc/introduction.txt
> Update current version in docs introduction

- pyNN/recording/__init__.py
Minor tweak: since we're comparing values here, "==" or "!=" should be used. ("is" compares identities).
> Use correct comparison operator

- pyNN/brian2/standardmodels/synapses.py
The current Brian2 support for STDP is broken. This pr fixes issue #711.
> Fix weight type in brain2 backend for issue 711

- pyNN/utility/__init__.py
- test/system/scenarios/test_connectors.py
- test/system/scenarios/test_parameter_handling.py
- test/system/scenarios/test_procedural_api.py
- test/system/scenarios/test_recording.py
- test/system/scenarios/test_simulation_control.py
- test/system/test_hardware_brainscales.py
- test/system/test_nest.py
- test/unittests/test_brian.py
- test/unittests/test_files.py
- test/unittests/test_parameters.py
- test/unittests/test_projection.py
- test/unittests/test_random.py
- test/unittests/test_recording.py
- test/unittests/test_space.py
> Replace testing functions from pyNN.utility with functions from numpy.testing

- pyNN/parameters.py
minor import tweak to keep the code py3.10 ready
> fix: correct sized import

- pyNN/brian2/populations.py
- pyNN/brian2/standardmodels/cells.py
- pyNN/nest/populations.py
- pyNN/neuron/populations.py
- pyNN/neuron/standardmodels/cells.py
- pyNN/parameters.py
- pyNN/standardmodels/cells.py
- test/unittests/test_parameters.py
(ParameterSets that contain other ParameterSets)
i.e. remove distinction between values and children. Also add a lot more tests of the `parameters` module.
> Simplify hierarchical ParameterSets 

- pyNN/nest/extensions/pynn_extensions.cpp
- pyNN/nest/extensions/simple_stochastic_synapse.h
- pyNN/nest/extensions/stochastic_stp_synapse.h
Fixes https://github.com/NeuralEnsemble/PyNN/issues/793
> fix(nest): correctly use namespaces
